include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # STYLE
    prefer_single_quotes: true
    always_declare_return_types: true
    require_trailing_commas: true

    # CODE QUALITY
    avoid_print: true
    avoid_dynamic_calls: true
    avoid_returning_null_for_void: true
    unnecessary_null_checks: true

    # READABILITY
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_child_properties_last: true

    # SAFETY
    cancel_subscriptions: true
    close_sinks: true

    # FLUTTER BEST PRACTICES
    use_build_context_synchronously: false # utile avec Riverpod


dcm:
  exclude-public-api: true

  metrics:
    cyclomatic-complexity:
      threshold: 15   # plus strict
    number-of-parameters:
      threshold: 4
    maximum-nesting-level:
      threshold: 4   # éviter les usines à gaz

  exclude:
    metrics:
      - test/**

  rules:
    - newline-before-return

    - avoid-non-null-assertion:
        message: 'Use safe access or custom helpers instead.'

    - avoid-dynamic
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-moving-to-variable
    - prefer-match-file-name
    - avoid-self-compare
    - avoid-self-assignment

    # 🔥 AJOUTS IMPORTANTS
    - prefer-extracting-callbacks
