name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # ou master selon votre branche principale

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: stable
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow tqdm

      - name: Verify assets/images folder exists
        run: |
          if [ ! -d "assets/images" ]; then
            echo "Erreur : le dossier assets/images est introuvable."
            exit 1
          else
            echo "Dossier assets/images trouvé."
          fi

      - name: Generate image asset variants
        run: |
          python generate_asset_variants.py --src assets/images --scales 2,3

      - name: Build Flutter Web
        run: flutter build web --base-href="/bat_track_v1/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
